use_frameworks!

target 'EpubExtractor_Example' do
  pod 'EpubExtractor', :path => '../'

  target 'EpubExtractor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
