use_frameworks!

target 'EpubExstractor_Example' do
  pod 'EpubExstractor', :path => '../'

  target 'EpubExstractor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
